# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  build-1:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: false
          from_artifact: false
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-2:
    needs: build-1
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-3:
    needs: build-2
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-4:
    needs: build-3
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-5:
    needs: build-4
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-6:
    needs: build-5
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-7:
    needs: build-6
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-8:
    needs: build-7
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-x86-1:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: false
          from_artifact: false
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-x86-2:
    needs: build-x86-1
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-x86-3:
    needs: build-x86-2
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-x86-4:
    needs: build-x86-3
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-x86-5:
    needs: build-x86-4
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-x86-6:
    needs: build-x86-5
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-x86-7:
    needs: build-x86-6
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-x86-8:
    needs: build-x86-7
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  publish-release:
    needs: [build-8, build-x86-8]
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: chromium
      - name: Download x86 package
        uses: actions/download-artifact@v2
        with:
          name: chromium-x86
      - name: Publish release
        id: publish
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          fail_on_unmatched_files: true
          files: |
            ungoogled-chromium*
    outputs:
      assets: ${{ steps.publish.outputs.assets }}
  publish-winget:
    needs: publish-release
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/winget
      - name: Run Stage
        id: stage
        uses: ./.github/actions/winget
        with:
          token: ${{ secrets.PAT }}
          version: ${{ github.ref_name }}
          assets: ${{ needs.publish-release.outputs.assets }}
